version: "3.8"

services:
  app:
    image: dev-scope:latest
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_PROFILE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health"]
      interval: 10s
      timeout: 5s
      retries: 5